### ISSUE TITLE
1.8.x build

### ISSUE THREAD

**Issue by mkazlauskas** [agracio/electron-edge-js#2]
Is it supposed to be working with Electron 1.8.x? I can install it with 1.7.x without problems, but 1.8.x will give me this:

```Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1```

**Comment by agracio** [comment]
Yes, it should work with Electron 1.8.x. What is the full error and is it on Windows?

**Comment by mkazlauskas** [comment]
It is on Windows. Getting the error when doing `electron-rebuild`:

```  Generating code
  Finished generating code
  edge_coreclr.vcxproj -> C:\Users\Martynas\Source\Repos\zamok-browser\app\node_modules\electron-edge-js\build\Release\\
edge_coreclr.node
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Martynas\Source\Repos\zamok-browser\node_modules\node-gyp\lib\build.
js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Martynas\\Source\\Repos\\zamok-browser\\node_mo
dules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=1.8.2-beta.2" "--arch=ia32" "--dist-url=https://atom.io/download/
electron" "--build-from-source"
gyp ERR! cwd C:\Users\Martynas\Source\Repos\zamok-browser\app\node_modules\electron-edge-js
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (C:\Users\Martynas\Source\Repos\zamok-browser\node_modules\spawn-rx\lib\src\index.js:277:84
)
    at SafeSubscriber.__tryOrUnsub (C:\Users\Martynas\Source\Repos\zamok-browser\node_modules\rxjs\Subscriber.js:238:16)

    at SafeSubscriber.error (C:\Users\Martynas\Source\Repos\zamok-browser\node_modules\rxjs\Subscriber.js:197:26)
    at Subscriber._error (C:\Users\Martynas\Source\Repos\zamok-browser\node_modules\rxjs\Subscriber.js:128:26)
    at Subscriber.error (C:\Users\Martynas\Source\Repos\zamok-browser\node_modules\rxjs\Subscriber.js:102:18)
    at MapSubscriber.Subscriber._error (C:\Users\Martynas\Source\Repos\zamok-browser\node_modules\rxjs\Subscriber.js:128
:26)
    at MapSubscriber.Subscriber.error (C:\Users\Martynas\Source\Repos\zamok-browser\node_modules\rxjs\Subscriber.js:102:
18)
    at SafeSubscriber._next (C:\Users\Martynas\Source\Repos\zamok-browser\node_modules\spawn-rx\lib\src\index.js:251:65)

    at SafeSubscriber.__tryOrUnsub (C:\Users\Martynas\Source\Repos\zamok-browser\node_modules\rxjs\Subscriber.js:238:16)

    at SafeSubscriber.next (C:\Users\Martynas\Source\Repos\zamok-browser\node_modules\rxjs\Subscriber.js:185:22)```

**Comment by agracio** [comment]
I am not sure about `electron-rebuild` as I have never used it myself, however the issue is likely with `node-gyp` build options. Version 1.8.x requires parameter msvs_version to be set to 2017 in order to build.

**Comment by agracio** [comment]
Excluding `electron-edge-js` from electron-rebuild should solve the problem.

**Comment by mkazlauskas** [comment]
Thanks for tips. Not building it has probably solved the problem for my particular use case, but I couldn't yet test it properly, still have a problem with another package.
